//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRunner.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSRunner.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BORICA OnLine - working in async mode..
        /// </summary>
        internal static string BORICA_ASYNC_OFF {
            get {
                return ResourceManager.GetString("BORICA_ASYNC_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BORICA OnLine - working offline..
        /// </summary>
        internal static string BORICA_AUTH_OFF {
            get {
                return ResourceManager.GetString("BORICA_AUTH_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database {0} ....
        /// </summary>
        internal static string CONNECTING_TO_DATABASE {
            get {
                return ResourceManager.GetString("CONNECTING_TO_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the database..
        /// </summary>
        internal static string CONNECTING_TO_FAIL {
            get {
                return ResourceManager.GetString("CONNECTING_TO_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string CONNECTING_TO_SUCCESS {
            get {
                return ResourceManager.GetString("CONNECTING_TO_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of working day..
        /// </summary>
        internal static string END_OF_DAY {
            get {
                return ResourceManager.GetString("END_OF_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is working as user: {0}, accounting period: {1}..
        /// </summary>
        internal static string RUNNING_TASK_ENV {
            get {
                return ResourceManager.GetString("RUNNING_TASK_ENV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task end with error #{0}..
        /// </summary>
        internal static string TASK_END_FAILD {
            get {
                return ResourceManager.GetString("TASK_END_FAILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task end successfully..
        /// </summary>
        internal static string TASK_END_SUCCESS {
            get {
                return ResourceManager.GetString("TASK_END_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} can&apos;t be used..
        /// </summary>
        internal static string USER_CANT_BE_USED {
            get {
                return ResourceManager.GetString("USER_CANT_BE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string USER_FAIL {
            get {
                return ResourceManager.GetString("USER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} can&apos;t be authenticated into accounting period {1}..
        /// </summary>
        internal static string USER_FAIL_AT_STID {
            get {
                return ResourceManager.GetString("USER_FAIL_AT_STID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication of user {0} ....
        /// </summary>
        internal static string USER_LOGIN {
            get {
                return ResourceManager.GetString("USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User don&apos;t belongs to group {0}..
        /// </summary>
        internal static string USER_NOT_MEMBER_OF {
            get {
                return ResourceManager.GetString("USER_NOT_MEMBER_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requesting end of the task..
        /// </summary>
        internal static string USER_REQUEST_PROGRAM_QUIT {
            get {
                return ResourceManager.GetString("USER_REQUEST_PROGRAM_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string USER_SUCCESS {
            get {
                return ResourceManager.GetString("USER_SUCCESS", resourceCulture);
            }
        }
    }
}
